### ISSUE TITLE
Cambios necesarios

### ISSUE THREAD

**Issue by hvarg** [J122016/INF322#1]
El componente de navegación tiene un buen funcionamiento, pero es necesario que se note en que parte estamos, basta con usar CSS para marcar la opción elegida.

![Screen Shot 2020-02-19 at 19 21 57](https://user-images.githubusercontent.com/15269912/74882289-983dde00-534d-11ea-8349-ffe537999d40.png)

También es necesario agregar un link a la página principal en el icono del header.

Además sería ideal si pueden agregar una página dummy de noticias para notar como el componente de navegación cambia el contenido de la página.

Por último, es bastante interesante que la búsqueda filtre la navegación, pero que el buscador esté al medio del `header` me hace pensar que será una búsqueda en texto del sistema, no un filtro a tiempo real. Si quieren dejarla como filtro en navegación, sería adecuado que el botón de búsqueda esté cerca de los menus que modifica.

**Comment by J122016** [comment]
Los cambios fueron realizados en la *branch dev*, específicamente en los commits subidos entre el 28/02 ([c4c72da](https://github.com/J122016/INF322/commit/c4c72da915d02b37ceb4b9140a4825722a38baee)) y 06/03 ([bbb5401]( https://github.com/J122016/INF322/commit/bbb5401547e55142e9c40a529d2e70e94390afb6 )).

Issues realizadas:
- [x] Resaltar opción elegida en menú.
- [x] Agregar link a pagina principal en icono del header.
- [x] Adición de páginas dummy y efecto de transición.
- [x] Traslado de filtro de navegación.
